# Generated by Django 4.2.17 on 2026-02-20 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, help_text='Unique student identification number', max_length=20, null=True, unique=True)),
                ('year_group', models.CharField(choices=[('year_7', 'Year 7'), ('year_8', 'Year 8'), ('year_9', 'Year 9'), ('year_10', 'Year 10'), ('year_11', 'Year 11')], default='year_7', max_length=10)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('observer', 'Observer')], default='student', max_length=10)),
                ('is_eligible', models.BooleanField(default=True, help_text='Whether the student is eligible to vote')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('publish', 'Published'), ('close', 'Closed'), ('export', 'Exported'), ('eligibility', 'Changed Eligibility')], max_length=20)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, help_text='The model type that was affected', max_length=50)),
                ('target_id', models.IntegerField(blank=True, help_text='The ID of the affected record', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
